---
abstract: 'Pod::Usage extracts POD documentation and shows usage information'
author:
  - 'Brad Appleton  <bradapp@enteract.com>'
  - 'Marek Rouchal <marekr@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.44, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Pod-Usage
no_index:
  directory:
    - t
    - inc
requires:
  Cwd: '0'
  File::Basename: '0'
  File::Spec: '0.82'
  Pod::Text: '4'
  Test::More: '0.6'
  blib: '0'
version: '1.70'
